name: CMake with Qt6 & OpenCV 4.12.0

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install basic build tools
    - name: Install basic tools
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake git curl unzip pkg-config

    # Install vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    # Install Qt6 and OpenCV via vcpkg
    - name: Install dependencies via vcpkg
      run: |
        ./vcpkg/vcpkg install qt6:x64-linux
        ./vcpkg/vcpkg install opencv[core,highgui,videoio]:x64-linux

    # Configure CMake with vcpkg toolchain
    - name: Configure CMake
      run: cmake -B $CameraSDK/OptiTrackCameraSDK_confidential_115_release-3.4.0_BUILD110/CameraSDK/samples/CameraViewerApp/build \
                -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    # Build
    - name: Build
      run: cmake --build $CameraSDK/OptiTrackCameraSDK_confidential_115_release-3.4.0_BUILD110/CameraSDK/samples/CameraViewerApp/build \
                --config ${{ env.BUILD_TYPE }}

    # Run tests
    - name: Test
      working-directory: $CameraSDK/OptiTrackCameraSDK_confidential_115_release-3.4.0_BUILD110/CameraSDK/samples/CameraViewerApp/build
      run: ctest -C ${{ env.BUILD_TYPE }}
